import 'meals.dart';

List<Meal> beefchikenList = [
  Meal(name: 'Grilled Rabbit', kcal: '193'),
  Meal(name: 'Boiled Rabbit', kcal: '194'),
  Meal(name: 'Geese', kcal: '349'),
  Meal(name: 'Grilled Veal', kcal: '278'),
  Meal(name: 'Reddish Veal', kcal: '512'),
  Meal(name: 'Duck', kcal: '170'),
  Meal(name: 'Roast Pigeon', kcal: '105'),
  Meal(name: 'Grilled Chicken', kcal: '130'),
  Meal(name: 'Turkey', kcal: '280'),
  Meal(name: 'Grilled Liver', kcal: '200'),
  Meal(name: 'Beef Steak', kcal: '273'),
  Meal(name: 'Lamp meat', kcal: '300'),
  Meal(name: 'Shawrma', kcal: '317'),
  Meal(name: 'Kabab', kcal: '226'),
  Meal(name: 'Pastrami', kcal: '280'),
  Meal(name: 'Sausage', kcal: '592'),
  Meal(name: 'Luncheon', kcal: '172'),
  Meal(name: 'Burger', kcal: '286'),
];
List<Meal> fruitList = [
  Meal(name: 'Pineapple', kcal: '38'),
  Meal(name: 'Orange', kcal: '27'),
  Meal(name: 'Water Melon', kcal: '16'),
  Meal(name: 'Balah', kcal: '214'),
  Meal(name: 'Fig', kcal: '79'),
  Meal(name: 'Apple', kcal: '58'),
  Meal(name: 'BlueBurry', kcal: '36'),
  Meal(name: 'GrapeFruit', kcal: '17'),
  Meal(name: 'Guava', kcal: '70'),
  Meal(name: 'Coconut', kcal: '336'),
  Meal(name: 'Peach', kcal: '36'),
  Meal(name: 'Pomegranate', kcal: '20'),
  Meal(name: 'Grape', kcal: '239'),
  Meal(name: 'Mango', kcal: '66'),
  Meal(name: 'Banana', kcal: '45'),
  Meal(name: 'Tangerine', kcal: '24'),
];
List<Meal> vegetableList = [
  Meal(name: 'Eggplant', kcal: '15'),
  Meal(name: 'Okka', kcal: '32'),
  Meal(name: 'Boiled', kcal: '49'),
  Meal(name: 'Onions', kcal: '23'),
  Meal(name: 'Potatos', kcal: '85'),
  Meal(name: 'Parsley', kcal: '28'),
  Meal(name: 'Beet', kcal: '44'),
  Meal(name: 'Rocca', kcal: '18'),
  Meal(name: 'Carrot', kcal: '45'),
  Meal(name: 'Lettuce', kcal: '11'),
  Meal(name: 'Cucumber', kcal: '12'),
  Meal(name: 'Spinach', kcal: '36'),
  Meal(name: 'Tomato', kcal: '20'),
  Meal(name: 'Zucchini', kcal: '26'),
  Meal(name: 'Mulukhiyah', kcal: '47'),
  Meal(name: 'Olive', kcal: '99'),
];
List<Meal> dairyList = [
  Meal(name: 'Full Skimmed Milk', kcal: '130'),
  Meal(name: 'Skimmed', kcal: '45'),
  Meal(name: 'Chocolate Milk', kcal: '550'),
  Meal(name: 'Yogurt', kcal: '55'),
  Meal(name: 'Fruit Yogurt', kcal: '106'),
  Meal(name: 'Rumi', kcal: '313'),
  Meal(name: 'Chedder', kcal: '398'),
  Meal(name: 'Flamengo', kcal: '370'),
  Meal(name: 'Cottage', kcal: '116'),
  Meal(name: 'Keri', kcal: '810'),
  Meal(name: 'Mozzarella', kcal: '80'),
];
List<Meal> eggList = [
  Meal(name: 'Boiled egg', kcal: '79'),
  Meal(name: 'Fried egg', kcal: '91'),
  Meal(name: 'Omelette', kcal: '92'),
];
List<Meal> nutsList = [
  Meal(name: 'Nut', kcal: '651'),
  Meal(name: 'Sesame', kcal: '595'),
  Meal(name: 'Pistachio', kcal: '594'),
];
List<Meal> dessertList = [
  Meal(name: 'Rice pudding', kcal: '144'),
  Meal(name: 'Basbosa', kcal: '480'),
  Meal(name: 'Halva', kcal: '516'),
  Meal(name: 'Cake', kcal: '350'),
  Meal(name: 'Jelly', kcal: '59'),
  Meal(name: 'Honey', kcal: '320'),
  Meal(name: 'Ghoriba', kcal: '521'),
  Meal(name: 'Corn Flakes', kcal: '367'),
  Meal(name: 'Konafa', kcal: '780'),
  Meal(name: 'Jam', kcal: '275'),
  Meal(name: 'Donat', kcal: '452'),
  Meal(name: 'Ice Cream', kcal: '207'),
];
List<Meal> coldDrinkList = [
  Meal(name: 'Mango', kcal: '110'),
  Meal(name: 'Guava', kcal: '175'),
  Meal(name: 'Orange', kcal: '118'),
  Meal(name: 'Apple', kcal: '120'),
  Meal(name: 'Cola', kcal: '97'),
  Meal(name: 'Diet Cola', kcal: '1'),
  Meal(name: 'MilkShake', kcal: '112'),
  Meal(name: 'Oreo MilkShake', kcal: '262'),
];
List<Meal> hotDrinkList = [
  Meal(name: 'Nescafe', kcal: '60'),
  Meal(name: 'Tea(0 sugar)', kcal: '1'),
  Meal(name: 'Hot Chocolate', kcal: '452'),
  Meal(name: 'American Coffee', kcal: '5'),
  Meal(name: 'Sahlab', kcal: '165'),
  Meal(name: 'Ginger', kcal: '69'),
  Meal(name: 'Latte', kcal: '42'),
  Meal(name: 'Flat White', kcal: '70'),
];
List<Meal> seafoodList = [
  Meal(name: 'Tilapia Fish', kcal: '100'),
  Meal(name: 'Smoked Fish', kcal: '85'),
  Meal(name: 'Grilled Mullet', kcal: '170'),
  Meal(name: 'Tuna', kcal: '280'),
  Meal(name: 'Shrimp', kcal: '90'),
  Meal(name: 'Smoked Herring', kcal: '189'),
  Meal(name: 'Grilled Salmon', kcal: '108'),
  Meal(name: 'Crab', kcal: '94'),
  Meal(name: 'Sushi', kcal: '230'),
];
